# Autogenerated wrapper script for libnabo_jll for armv6l-linux-gnueabihf-cxx11
export libnabo

using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("libnabo")
JLLWrappers.@declare_library_product(libnabo, "libnabo.so.1")
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll)
    JLLWrappers.@init_library_product(
        libnabo,
        "lib/libnabo.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
